### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by jottinger** [evanchooly/javabot#111]
On a newly forked repository *and* the upstream:

Joseph@netzach ~/work/java/javabot
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Joseph@netzach ~/work/java/javabot
$ mvn clean compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] javabot
[INFO] javabot core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building javabot 6.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ javabot ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building javabot core 6.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ core ---
[INFO] Deleting C:\cygwin64\home\Joseph\work\java\javabot\core\target
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (jacoco-initialize) @ core ---
[INFO] argLine set to -javaagent:C:\\Users\\Joseph\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.2.201409121644\\org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=C:\\cygwin64\\home\\Joseph\\work\\java\\javabot\\core\\target\\jacoco.exec,excludes=javabot.model.criteria.*:javabot.javadoc.criteria.*
[INFO]
[INFO] --- sofia-maven:0.15:generate (default) @ core ---
Generating code in to C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\com\antwerkz\sofia\Sofia.java
[INFO]
[INFO] --- critter-maven:2.1.0:generate (critter) @ core ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 45 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ core ---
[INFO] Compiling 143 source files to C:\cygwin64\home\Joseph\work\java\javabot\core\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\AdminDao.java:[11,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ChannelDao.java:[12,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\LogsDao.java:[6,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ShunDao.java:[6,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\EventDao.java:[5,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\operations\throttle\Throttler.java:[19,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\NickServDao.java:[9,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\NickServDao.java:[10,50] error: package javabot.model.criteria.NickServInfoCriteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\KarmaDao.java:[7,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ChangeDao.java:[7,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ApiDao.java:[7,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[3,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[4,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[5,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\FactoidDao.java:[8,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\operations\LogsOperation.java:[6,29] error: package javabot.model.criteria does not exist
[INFO] 16 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] javabot ............................................ SUCCESS [  0.125 s]
[INFO] javabot core ....................................... FAILURE [  4.511 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.761 s
[INFO] Finished at: 2015-06-26T13:31:54-04:00
[INFO] Final Memory: 24M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project core: Compilation failure: Compilation failure:
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\AdminDao.java:[11,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ChannelDao.java:[12,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\LogsDao.java:[6,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ShunDao.java:[6,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\EventDao.java:[5,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\operations\throttle\Throttler.java:[19,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\NickServDao.java:[9,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\NickServDao.java:[10,50] error: package javabot.model.criteria.NickServInfoCriteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\KarmaDao.java:[7,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ChangeDao.java:[7,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\ApiDao.java:[7,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[3,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[4,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\JavadocClassDao.java:[5,31] error: package javabot.javadoc.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\dao\FactoidDao.java:[8,29] error: package javabot.model.criteria does not exist
[ERROR] C:\cygwin64\home\Joseph\work\java\javabot\core\src\main\java\javabot\operations\LogsOperation.java:[6,29] error: package javabot.model.criteria does not exist
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

Joseph@netzach ~/work/java/javabot
$

**Comment by evanchooly** [comment]
because of a bug in the critter maven plugin, you need to compile from core manually

**Comment by evanchooly** [comment]
fixed
