### ISSUE TITLE
Limit size of javabot replies

### ISSUE THREAD

**Issue by whaley** [evanchooly/javabot#120]
Bot needs a hard limit on the size of the message it sends.  You can use the ~yalla factoid to reproduce what might happen if this were abused.

>015-09-02 09:28:27	whaley	~yalla will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day
>2015-09-02 09:28:28	javabot	will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you
>2015-09-02 09:28:29	javabot	ot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabro
>2015-09-02 09:28:30	javabot	buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_
>2015-09-02 09:28:31	javabot	it_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day w
>2015-09-02 09:28:32	javabot	llo_ron_you_are_jabroni_have_a_good_day will_javabot_exceed_buffer_limit_also_hello_ron_you_are_jabroni_have_a_good_day !111!!!!!one!!!

**Comment by evanchooly** [comment]
GetFactoidOperation should probably truncate responses to the irc line length.

**Comment by evanchooly** [comment]
limiting response lengths to 510 characters per https://tools.ietf.org/html/rfc2812
