### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jottinger** [evanchooly/javabot#127]
How to run and/or test the web interface

**Comment by jottinger** [comment]
After copying javabot-sample.yml to javabot.yml, mvn test yields the following failure:

Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@5e25a92e
Jan 15, 2016 12:49:08 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
javabot.yml has an error:
  * Failed to parse configuration at: logging.loggers; Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class ch.qos.logback.classic.Level]] from String value (''); no single-String constructor/factory method (through reference chain: javabot.kotlin.web.JavabotConfiguration["logging"]->io.dropwizard.logging.LoggingFactory["loggers"])

**Comment by jottinger** [comment]
Actually, it's not even clear to me how to use IDEA on javabot any more - Sofia no longer resolves. I'm pretty sure there are a few fairly simple steps to go from "where it is" to "I can work with it" but they're not obvious to me nor are they documented anywhere.

**Comment by evanchooly** [comment]
what does "Sofia no longer resolves" mean?  If you build with maven it should be auto-generated.

**Comment by jottinger** [comment]
After compilation with maven, IDEA still shows Sofia references as unresolved; the extra source tree for Sofia isn't being included in the IDEA classpath.

**Comment by whaley** [comment]
>After compilation with maven, IDEA still shows Sofia references as unresolved; the extra source tree for Sofia isn't being included in the IDEA class path.

That has to do with <build><sourceDirectory> being overriden in pom.xml to src/main/kotlin.  The maven-compiler-plugin will still use src/main/java during the compile phase, but Idea is only looking at sourceDirectory to evaluate its own class path.  

Do something like this to make add src/main/java to the class path:
<img width="720" alt="screen shot 2016-01-16 at 10 35 11 am" src="https://cloud.githubusercontent.com/assets/166648/12373136/1feeb254-bc3d-11e5-8d37-b7a96a0677fd.png">

**Comment by jottinger** [comment]
That makes perfect sense, although I ended up having to do it through modification of the javabot.iml directly, adding `<sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false" />` to the configuration. Progress made. We need to add that to the README for future developers.
