### ISSUE TITLE
Would be nice to have a ~previnfo or other way to restore an overwritten factoid.

### ISSUE THREAD

**Issue by rzwitserloot** [evanchooly/javabot#169]
_feature request_

When some hooligan overwrites a factoid, or it is done accidentally, it would be nice if we can in-channel look up what just got overwritten.

This can take the form of: `~restore <factoid name>`
or: `~previnfo <factoid name>`

or something else.

**Comment by evanchooly** [comment]
I wrote this a while back for that very reason but I haven't integrated it to the bot yet:  https://github.com/evanchooly/lariat

**Comment by evanchooly** [comment]
duplicate of #16
