### ISSUE TITLE
sensitive to leading space before ~

### ISSUE THREAD

**Issue by jottinger** [evanchooly/javabot#204]
```
08:09 <@dreamreal>  ~ odinsbane ++
08:09 <@dreamreal> ~ odinsbane ++
08:09 <javabot> odinsbane has a karma level of 57, dreamreal
```

Intentional?

**Comment by evanchooly** [comment]
in coming messages are not trimmed.  Was that intentional?  not really.  i just haven't been terribly motivated to provide a fix for others' typos.  :)

**Comment by jottinger** [comment]
Well, it has some use - it allows one to demonstrate the bot operations
without invoking them. That may be worth keeping as a "feature."

**Comment by evanchooly** [comment]
my thoughts exactly.  close the bug, i think?

**Comment by jottinger** [comment]
Works for me.
