### ISSUE TITLE
Invoking a factoid that has $1 should not result in a response if $1 isn't specified

### ISSUE THREAD

**Issue by whaley** [evanchooly/javabot#208]
An example:
```
8:07 <whaley> ~ball
18:07  * javabot kicks  in the ball.
18:07 <@dreamreal> see?
18:07 <@dreamreal> That should be a non-answer.
```

**Comment by whaley** [comment]
This could default to the nick who sent the message.

**Comment by jottinger** [comment]
I think it should just quietly error out.

**Comment by whaley** [comment]
I don't think there's a case where invoking javabot directly ever results in a non-response.  It always at least responds with something, e.g. `what does that even *mean*?` on a bad factoid look up.  A non-response would give the immediate impression the bot isn't available.

**Comment by jottinger** [comment]
Well, there is with THIS patch.

"javabot's just taking a powder" <-- now results in no content, as expected
"javabot is taking a powder" <-- gets the "what does that mean?" response,
as should be expected as most such references won't be referring to
javabot's status

**Comment by whaley** [comment]
Resolve?

**Comment by evanchooly** [comment]
I think so.  If not, it can be reopened
