### ISSUE TITLE
URLTitleOperation shows the pic.twitter.com which should be hidden

### ISSUE THREAD

**Issue by kinabalu** [evanchooly/javabot#234]
seems to only be a Twitter-related thing, here's an example tweet: https://twitter.com/TheOnion/status/1080887787266674690

when this URL is pulled, the title it pulls from also has a photo, and twitter has a div block aside from the photo itself which is not meant to be shown on the frontend, but since the URLTitleOperation is not smart, it pulls all:

```
<a href="https://t.co/Qyg7DUpqre" class="twitter-timeline-link u-hidden" data-pre-embedded="true" dir="ltr">pic.twitter.com/Qyg7DUpqre</a>```

**Comment by jottinger** [comment]
Actually, this LOOKS LIKE a problem in Jsoup, not respecting whitespace in `text()` - there are blocks in that url content that should be represented by at least one whitespace in the output. This might be "fun."

**Comment by jottinger** [comment]
Okay, looking at THE ORIGINAL HTML source, it looks like this:

    <div class="js-tweet-text-container">
  <p class="TweetTextSize TweetTextSize--jumbo js-tweet-text tweet-text" lang="en" data-aria-label-part="0">Meghan McCain Forced To Live Out Socialist Nightmare Of Empathy For Sick Person <a href="https://t.co/HehkZvBbwz" rel="nofollow noopener" dir="ltr" data-expanded-url="https://trib.al/6EXfUh5" class="twitter-timeline-link" target="_blank" title="https://trib.al/6EXfUh5" ><span class="tco-ellipsis"></span><span class="invisible">https://</span><span class="js-display-url">trib.al/6EXfUh5</span><span class="invisible"></span><span class="tco-ellipsis"><span class="invisible">&nbsp;</span></span></a> <a href="/hashtag/OurAnnualYear2018?src=hash" data-query-source="hashtag_click" class="twitter-hashtag pretty-link js-nav" dir="ltr" ><s>#</s><b>OurAnnualYear2018</b></a><a href="https://t.co/Qyg7DUpqre" class="twitter-timeline-link u-hidden" data-pre-embedded="true" dir="ltr" >pic.twitter.com/Qyg7DUpqre</a></p>
</div>

That's annoying, but I THINK the rendering from JSoup is actually correct. There's a whitespace before "OurAnnualYear2018" --- but not after, so JSoup is rendering the bare link text immediately after.
