### ISSUE TITLE
Weather API is no longer available

### ISSUE THREAD

**Issue by jottinger** [evanchooly/javabot#240]
Possibly use https://openweathermap.org/current instead

**Comment by jottinger** [comment]
Other thoughts: remember what the user last requested and use that as a default location. Other possibilities include trying to derive where the user is (if exposed; how to validate?) and using regions close to that.

**Comment by freeone3000** [comment]
I'd like if it didn't use the null weather from Montreal, Bahamas over the weather for Montreal, Quebec simply because B comes before Q.

**Comment by freeone3000** [comment]
I don't agree. OWM's free tier of API access should more than suffice for the needs of any IRC channel. We'd have to do credential management, but there's not an ongoing additional monetary cost solely for weather data. I believe that the social feature that this weather service provides (showing off Florida weather in the winter) does outweigh this risk.

**Comment by jottinger** [comment]
API keys, not "paid API keys." I'm neutral about whether we keep the operation or not... but if the code's there, it should be required to work.
