### ISSUE TITLE
java-browser support

### ISSUE THREAD

**Issue by yawkat** [evanchooly/javabot#257]
https://java-browser.yawk.at/ has source files for the JDK and many libraries. If I add an API to java-browser, javabot could link to source files using for example `~source String`. Additionally, there could be artifact filtering, eg. `~source java/8 String`.

**Comment by yawkat** [comment]
@jottinger suggested instead simply creating a page on java-browser that would do the search instead of going through an api. In my opinion this is additional friction for the user, and the implementation effort on my side is similar if not higher than simply exposing an API, but a decision depends on the work required on the javabot side.

**Comment by yawkat** [comment]
This is my prototype for the API: https://java-browser.yawk.at/api/javabotSearch/v1?term=Files&artifact=guava

The `artifact` parameter is optional, leaving it off will simply search all artifacts. The term parameter can take class, package, field and method names in qualified and unqualified forms.

**Comment by jottinger** [comment]
Merged
