### ISSUE TITLE
Karma DB out of sync?

### ISSUE THREAD

**Issue by Maldivia** [evanchooly/javabot#277]
"maldivia" is currently listed twice in the database, currently with the following entries:
```
maldivia     290     matsurago     2020.04.27 06:04    https://javabot.evanchooly.com/karma?page=1
maldivia       3     Chronos       2020.05.18 09:57    https://javabot.evanchooly.com/karma?page=14
```

**Comment by jottinger** [comment]
This looks like an underlying data issue, caused by a, um, restore of data. But it does lead to exposing a different cosmetic issue.
