### ISSUE TITLE
Funky karma change behavior

### ISSUE THREAD

**Issue by webron** [evanchooly/javabot#51]
Observe the following:
mrcheeks: ~~L-----D google java embedded nosql
javabot: ~l has a karma level of -2, mrcheeks

And then:
ron: ~tell L-----D about google java embedded nosql
javabot: tell l has a karma level of -1, ron

And yes, the username was L-----D.

**Comment by jottinger** [comment]
What operation handles tell? Could it be set to a higher priority than karma, which would fix this problem?

**Comment by evanchooly** [comment]
Tells are part of GetFactoidOperation which is always last in the chain.  requiring the ++ or -- to be at the end of the line or followed by a space would be fine, i think.

**Comment by jottinger** [comment]
So no more karma comments?

**Comment by evanchooly** [comment]
no, i think the point was to preserve that feature but limit false matches
